# サイト情報
title: "Shunji Sato Portfolio"    # サイトのタイトル
description: >                    # サイトの説明
  
author:
  name: "Shunji Sato"
  url: "https://oshunjis.net"

# テーマ
theme: minima                     # 使用するテーマ (既に設定済み)

# リンク (必要に応じて編集)
social_links:
  - name: X
    url: "https://x.com/oshunjis"

# ページの設定
markdown: kramdown
permalink: pretty

# ナビゲーションリンク
header_pages:
  - about.markdown
  - index.markdown
  - blog.markdown

  show_rss_feed: false